create table public.offer_order_match_delivery_history (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    new_delivery_status public.delivery_status null,
    old_delivery_status public.delivery_status null,
    oom_id uuid null,
    updated_by text null,
    role text not null,
    constraint offer_order_match_delivery_history_pkey primary key (id),
    constraint offer_order_match_delivery_history_oom_id_fkey foreign KEY (oom_id) references offer_order_match (oom_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;